//
//  RegistrationWorker.swift
//  SeoulParking
//
//  Created by byeonggeunSon on 2020/02/06.
//  Copyright (c) 2020 손병근. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegistrationWorker
{
  func doSomeWork()
  {
  }
}
